name: Build and Deploy script

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=frontend/dist
        env:
          CI: true
          GH_TOKEN: ${{ secrets.Portfolio }} 

